function GUItest
close all
clear all
global fc tm bw radar_speed bw_INT tm_INT
global tx_power tx_loss rx_noise rx_loss rad_pat
global car_init_pos targVel targRange
global N_sweeps scenType
global data

f = figure('OuterPosition',[200 200 700 550]);

% Reference edges
leftTit = 30;
botTit = 400;
leftTB = 250;

leftTit1 = 400;
botTit1 = 200;
% leftTB1 = 

%% General Parameters
% Labels and Titles
tbTitle1 = uicontrol(f,'Style','text',...
                'String','General Radar Parameters',...
                'HorizontalAlignment','left',...
                'FontSize',16,...
                'Position',[leftTit botTit 200 30]);
            
lbfc = uicontrol(f,'Style','text',...
                'String','Center Frequency (2-3 GHz)',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[leftTit+20 botTit-25 200 30]);
            
lbtm = uicontrol(f,'Style','text',...
                'String','Chirp Period (ms)',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[leftTit+20 botTit-50 200 30]);

lbbw = uicontrol(f,'Style','text',...
                'String','Bandwidth (1-1000 MHz)',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[leftTit+20 botTit-75 200 30]);

lbVel = uicontrol(f,'Style','text',...
                'String','Radar Speed (0-100 m/s)',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[leftTit+20 botTit-100 200 30]);
            
lbIbw = uicontrol(f,'Style','text',...
                'String','Interferer Bandwidth (1-1000 MHz)',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[leftTit+20 botTit-125 200 30]);
            
lbItm = uicontrol(f,'Style','text',...
                'String','Interferer Chirp Period (ms)',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[leftTit+20 botTit-150 200 30]);

% Editable items
tbfc = uicontrol(f,'Style','edit','FontSize',12,...
                'Position',[leftTB 387 40 20]);
            
poptm = uicontrol(f,'Style','pop',...
                'FontSize',12,...
                'String',{'20','40'},...
                'Position',[leftTB-5 362 65 20]);   
poptmList = get(poptm,'string');
            
tbbw = uicontrol(f,'Style','edit','FontSize',12,...
                'Position',[leftTB 337 40 20]);            
            
tbVel = uicontrol(f,'Style','edit','FontSize',12,...
                'Position',[leftTB 312 40 20]);
            
tbIbw = uicontrol(f,'Style','edit','FontSize',12,...
                'Position',[leftTB 287 40 20]);            

popItm = uicontrol(f,'Style','pop',...
                'FontSize',12,...
                'String',{'20','40'},...
                'Position',[leftTB-5 262 65 20]);    
popItmList = get(popItm,'string');         
                        
%% Antenna Parameters
% Labels and Titles
tbTitle2 = uicontrol(f,'Style','text',...
                'String','Antenna Parameters',...
                'HorizontalAlignment','left',...
                'FontSize',16,...
                'Position',[leftTit+5 botTit1 200 30]);
      
align([tbTitle1,tbTitle2],'left','none') 

lbtxP = uicontrol(f,'Style','text',...
                'String','TX Power (W)',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[leftTit+20 botTit1-25 200 30]);
            
lbtxL = uicontrol(f,'Style','text',...
                'String','TX Loss Factor',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[leftTit+20 botTit1-50 200 30]);

lbrxN = uicontrol(f,'Style','text',...
                'String','RX Noise Figure (W)',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[leftTit+20 botTit1-75 200 30]);

lbrxL = uicontrol(f,'Style','text',...
                'String','RX Loss Factor',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[leftTit+20 botTit1-100 200 30]);
            
lbrpat = uicontrol(f,'Style','text',...
                'String','Radiation Pattern',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[leftTit+20 botTit1-125 200 30]);            

% Editable items    
tbtxP = uicontrol(f,'Style','edit',...
                'String','0.65','FontSize',12,...
                'Position',[leftTB 187 40 20]);            
            
tbtxL = uicontrol(f,'Style','edit',...
                'String','0','FontSize',12,...
                'Position',[leftTB 162 40 20]);            
            
tbrxN = uicontrol(f,'Style','edit',...
                'String','4.5','FontSize',12,...
                'Position',[leftTB 137 40 20]);
            
tbrxL = uicontrol(f,'Style','edit',...
                'String','0','FontSize',12,...
                'Position',[leftTB 112 40 20]);            

poprpat = uicontrol(f,'Style','pop',...
                'FontSize',12,'FontSize',12,...
                'String',{'TP Link','Patch','Directional'},...
                'Position',[leftTB-5 87 110 20]);
poprpatList = get(poprpat,'string');    

%% Target Parameters
% Title and labels
tbTitle3 = uicontrol(f,'Style','text',...
                'String','Target Parameters',...
                'HorizontalAlignment','left',...
                'FontSize',16,...
                'Position',[400 200 200 30]);
      
align([tbTitle1,tbTitle3],'none','top')

lbinitPos = uicontrol(f,'Style','text',...
                'String','Initial Position',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[420 botTit-25 130 30]);
            
lbxLoc = uicontrol(f,'Style','text',...
                'String','x-Location',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[435 botTit-50 130 30]);    
            
lbyLoc = uicontrol(f,'Style','text',...
                'String','y-Location',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[435 botTit-75 130 30]);               

lbTargVel = uicontrol(f,'Style','text',...
                'String','Velocity (0-100 m/s)',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[420 botTit-100 130 30]);

lbTargRan = uicontrol(f,'Style','text',...
                'String','Range (1-100 m)',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[420 botTit-125 130 30]);

% Editable Items
tbxLoc = uicontrol(f,'Style','edit','FontSize',12,...
                'Position',[550 362 40 20]);
            
tbyLoc = uicontrol(f,'Style','edit','FontSize',12,...
                'Position',[550 337 40 20]);            
            
tbTargVel = uicontrol(f,'Style','edit','FontSize',12,...
                'Position',[550 312 40 20]);
            
tbTargRan = uicontrol(f,'Style','edit','FontSize',12,...
                'Position',[550 287 40 20]);    
%% Simulation Settings
% Titles and labels
tbTitle4 = uicontrol(f,'Style','text',...
                'String','Simulation Settings',...
                'HorizontalAlignment','left',...
                'FontSize',16,...
                'Position',[400 200 200 30]);
      
align([tbTitle3,tbTitle4],'left','none')
align([tbTitle2,tbTitle4],'none','top')

lbNumSw = uicontrol(f,'Style','text',...
                'String','Number of Sweeps (even number 8-32)',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[420 botTit1-25 130 30]);
            
lbScen = uicontrol(f,'Style','text',...
                'String','Desired Scenario',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[420 botTit1-65 200 30]); 

% lbPlot = uicontrol(f,'Style','text',...
%                 'String','Output Plots',...
%                 'HorizontalAlignment','left',...
%                 'FontSize',12,...
%                 'Position',[420 110 200 30]);            

% Editable Items
tbNumSw = uicontrol(f,'Style','edit','FontSize',12,...
                'Position',[550 180 40 20]); 
            
popScen = uicontrol(f,'Style','pop',...
                'FontSize',12,'FontSize',12,...
                'String',{'1','2','3','4','Custom'},...
                'Position',[545 150 95 20]);    

%% Buttons              
pbNext = uicontrol(f,'Style','pushbutton','String','Next',...
                    'FontSize',12,'Position',[585 20 75 30],...
                    'Callback',@pbNext_Callback);
                
pbCancel = uicontrol(f,'Style','pushbutton','String','Cancel',...
                    'FontSize',12,'Position',[500 20 75 30],...
                    'Callback',@pbCancel_Callback);
              
%% Callback Functions
    
    function pbNext_Callback(source,callbackdata)
       display('Next Pressed')
       
       % RECORD INPUTS
       % General Radar Parameters
       fc = str2double(get(tbfc,'string'));
       tmVal = get(poptm,'value');
       tm = str2double(poptmList{tmVal});
       bw = str2double(get(tbbw,'string'));
       radar_speed = str2double(get(tbVel,'string'));
       bw_INT = str2double(get(tbIbw,'string'));
       tm_INTVal = get(popItm,'value');
       tm_INT = str2double(popItmList{tm_INTVal});
       
       % Antenna Parameters
       tx_power = str2double(get(tbtxP,'string'));
       tx_loss = str2double(get(tbtxL,'string'));
       rx_noise = str2double(get(tbrxN,'string'));
       rx_loss = str2double(get(tbrxL,'string'));
       rad_patVal = get(poprpat,'value');
       rad_pat = poprpatList{rad_patVal};
       
       % Target Parameters
       xLoc = str2double(get(tbxLoc,'string'));
       yLoc = str2double(get(tbyLoc,'string'));
       car_init_pos = [xLoc yLoc];
       targVel = str2double(get(tbTargVel,'string'));
       targRange = str2double(get(tbTargRan,'string'));
              
       % Simulation Settings
       N_sweeps = str2double(get(tbNumSw,'string'));
       scenType = get(popScen,'value');
       
       error = 0;
       % VERIFY ALL INPUTS ARE VALID
       % General Radar Parameters
       if isnan(fc)||fc<2||fc>3
           error = 1;
       end
       
       if isnan(bw)||bw<1||bw>1000
           error = 1;
       end
       
       if isnan(radar_speed)||radar_speed<0||radar_speed>100
           error = 1;
       end
       
       if isnan(bw_INT)||bw_INT<1||bw_INT>1000
           error = 1;
       end
       
       % Antenna Parameters
       if isnan(tx_power)
           error = 1;
       end
       
       if isnan(tx_loss)
           error = 1;
       end
       
       if isnan(rx_noise)
           error = 1;
       end
       
       if isnan(rx_loss)
           error = 1;
       end
       
       % Target Parameters
       if isnan(xLoc)
           error = 1;
       end
       
       if isnan(yLoc)
           error = 1;
       end
       
       if isnan(targVel)||targVel<0||targVel>100
           error = 1;
       end
       
       if isnan(targRange)||targRange<1||targRange>100
           error = 1;
       end
       
       % Simulation Settings
       if isnan(N_sweeps)||N_sweeps<8||N_sweeps>32
           error = 1;
       end
       
       
       if error == 1 
          errordlg('Check that input values are within ranges.','Invalid Input','modal')
          return
       end
       
       display(scenType)
       
       if scenType == 1
            display('1 Selected');
       elseif scenType == 2
            display('2 Selected');
       elseif scenType == 3
            display('3 Selected');
       elseif scenType == 4
            display('4 Selected');
       else
            close(gcf)
            display('Custom Selected');
            numIntdlg
       end
       display('------------------');
                       
    end

    function pbCancel_Callback(source,callbackdata)
       display('Program Cancelled')
       display('------------------');
       close(gcf)
       clear all
    end

    
end