function GUItest
close all
clear all
global fc tm bw radar_speed bw_INT tm_INT
global txPower txLossFactor rxNF rxLossFactor rad_pat
global car_init_pos car_speed targRange
global Nsweep scenType

f = figure('OuterPosition',[200 200 700 650]);

% Reference edges
leftTit = 30;
botTit = 400;
leftTB = 250;

leftTit1 = 400;
botTit1 = 200;

botTit2 = botTit+100;
% leftTB1 = 

%% Simulation Settings
% Titles and labels
tbTitle1 = uicontrol(f,'Style','text',...
                'String','Simulation Settings',...
                'HorizontalAlignment','left',...
                'FontSize',16,...
                'Position',[leftTit botTit2 200 30]);

lbNumSw = uicontrol(f,'Style','text',...
                'String','Number of Sweeps (even number 8-32)',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[leftTit+20 botTit2-25 130 30]);
            
lbScen = uicontrol(f,'Style','text',...
                'String','Desired Scenario',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[leftTit+20 botTit2-65 200 30]); 

% lbPlot = uicontrol(f,'Style','text',...
%                 'String','Output Plots',...
%                 'HorizontalAlignment','left',...
%                 'FontSize',12,...
%                 'Position',[420 110 200 30]);            

% Editable Items
tbNumSw = uicontrol(f,'Style','edit','FontSize',12,...
                'String','8',...
                'Position',[leftTit+150 botTit2-20 40 20]); 
            
popScen = uicontrol(f,'Style','pop',...
                'FontSize',12,...
                'String',{'1','2','3','4','Custom'},...
                'Position',[leftTit+145 botTit2-53 95 20],...
                'Callback',@scen_Callback);   
            
%% General Parameters
% Labels and Titles
tbTitle2 = uicontrol(f,'Style','text',...
                'String','General Radar Parameters',...
                'HorizontalAlignment','left',...
                'FontSize',16,...
                'Position',[leftTit botTit 200 30]);
            
lbfc = uicontrol(f,'Style','text',...
                'String','Center Frequency (2-3 GHz)',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[leftTit+20 botTit-25 200 30]);
            
lbtm = uicontrol(f,'Style','text',...
                'String','Chirp Period (ms)',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[leftTit+20 botTit-50 200 30]);

lbbw = uicontrol(f,'Style','text',...
                'String','Bandwidth (1-1000 MHz)',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[leftTit+20 botTit-75 200 30]);
            
lbIbw = uicontrol(f,'Style','text',...
                'String','Interferer Bandwidth (1-1000 MHz)',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[leftTit+20 botTit-100 200 30]);
            
lbItm = uicontrol(f,'Style','text',...
                'String','Interferer Chirp Period (ms)',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[leftTit+20 botTit-125 200 30]);

% Editable items
tbfc = uicontrol(f,'Style','edit','FontSize',12,...
                'String','2.445','Enable','off',...
                'Position',[leftTB 387 40 20]);
            
poptm = uicontrol(f,'Style','pop',...
                'FontSize',12,'Enable','off',...
                'String',{'20','40'},'Value',2,...
                'Position',[leftTB-5 362 65 20]);   
poptmList = get(poptm,'string');
            
tbbw = uicontrol(f,'Style','edit','FontSize',12,...
                'String','70','Enable','off',...
                'Position',[leftTB 337 40 20]);  
            
            
tbIbw = uicontrol(f,'Style','edit','FontSize',12,...
                'String','70','Enable','off',...
                'Position',[leftTB 312 40 20]);            

popItm = uicontrol(f,'Style','pop',...
                'FontSize',12,'Enable','off',...
                'String',{'20','40'},'Value',2,...
                'Position',[leftTB-5 287 65 20]);    
popItmList = get(popItm,'string');         
                        
%% Antenna Parameters
% Labels and Titles
tbTitle3 = uicontrol(f,'Style','text',...
                'String','Antenna Parameters',...
                'HorizontalAlignment','left',...
                'FontSize',16,...
                'Position',[leftTit+5 botTit1 200 30]);
      
align([tbTitle2,tbTitle3],'left','none') 

lbtxP = uicontrol(f,'Style','text',...
                'String','TX Power (W)',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[leftTit+20 botTit1-25 200 30]);
            
lbtxL = uicontrol(f,'Style','text',...
                'String','TX Loss Factor',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[leftTit+20 botTit1-50 200 30]);

lbrxN = uicontrol(f,'Style','text',...
                'String','RX Noise Figure (W)',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[leftTit+20 botTit1-75 200 30]);

lbrxL = uicontrol(f,'Style','text',...
                'String','RX Loss Factor',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[leftTit+20 botTit1-100 200 30]);
            
lbrpat = uicontrol(f,'Style','text',...
                'String','Radiation Pattern',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[leftTit+20 botTit1-125 200 30]);            

% Editable items    
tbtxP = uicontrol(f,'Style','edit',...
                'String','0.65','FontSize',12,'Enable','off',...
                'Position',[leftTB 187 40 20]);            
            
tbtxL = uicontrol(f,'Style','edit',...
                'String','0','FontSize',12,'Enable','off',...
                'Position',[leftTB 162 40 20]);            
            
tbrxN = uicontrol(f,'Style','edit',...
                'String','4.5','FontSize',12,'Enable','off',...
                'Position',[leftTB 137 40 20]);
            
tbrxL = uicontrol(f,'Style','edit',...
                'String','0','FontSize',12,'Enable','off',...
                'Position',[leftTB 112 40 20]);            

poprpat = uicontrol(f,'Style','pop',...
                'FontSize',12,'Enable','off',...
                'String',{'TP Link','Patch','Directional'},...
                'Position',[leftTB-5 87 110 20]);
poprpatList = get(poprpat,'string');   

%% Main System Parameters
tbTitle4 = uicontrol(f,'Style','text',...
                'String','Main System Parameters',...
                'HorizontalAlignment','left',...
                'FontSize',16,...
                'Position',[leftTit1 botTit 200 30]);
            
align([tbTitle2,tbTitle4],'none','bottom')  

lbinitPos_ms = uicontrol(f,'Style','text',...
                'String','Initial Position',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[420 botTit-25 130 30]);
            
lbxLoc_ms = uicontrol(f,'Style','text',...
                'String','x-Location',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[435 botTit-50 130 30]);    
            
lbyLoc_ms = uicontrol(f,'Style','text',...
                'String','y-Location',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[435 botTit-75 130 30]);               

lbms_speed = uicontrol(f,'Style','text',...
                'String','Speed (0-100 m/s)',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[420 botTit-100 130 30]);

% Editable Items
tbxLoc_ms = uicontrol(f,'Style','edit','FontSize',12,...
                'String','0','Enable','off',...
                'Position',[550 botTit-38 40 20]);
            
tbyLoc_ms = uicontrol(f,'Style','edit','FontSize',12,...
                'String','0','Enable','off',...
                'Position',[550 botTit-63 40 20]);            
            
tbms_speed = uicontrol(f,'Style','edit','FontSize',12,...
                'String','0','Enable','off',...
                'Position',[550 botTit-88 40 20]);       

%% Target Parameters
% Title and labels
tbTitle5 = uicontrol(f,'Style','text',...
                'String','Target Parameters',...
                'HorizontalAlignment','left',...
                'FontSize',16,...
                'Position',[leftTit1 200 200 30]);
      
align([tbTitle3,tbTitle5],'none','top')

lbinitPos = uicontrol(f,'Style','text',...
                'String','Initial Position',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[420 botTit1-25 130 30]);
            
lbxLoc = uicontrol(f,'Style','text',...
                'String','x-Location',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[435 botTit1-50 130 30]);    
            
lbyLoc = uicontrol(f,'Style','text',...
                'String','y-Location',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[435 botTit1-75 130 30]);               

lbcar_speed = uicontrol(f,'Style','text',...
                'String','Speed (0-100 m/s)',...
                'HorizontalAlignment','left',...
                'FontSize',12,...
                'Position',[420 botTit1-100 130 30]);

% Editable Items
tbxLoc = uicontrol(f,'Style','edit','FontSize',12,...
                'String','10','Enable','off',...
                'Position',[550 botTit1-38 40 20]);
            
tbyLoc = uicontrol(f,'Style','edit','FontSize',12,...
                'String','0','Enable','off',...
                'Position',[550 botTit1-63 40 20]);            
            
tbcar_speed = uicontrol(f,'Style','edit','FontSize',12,...
                'String','428.5714','Enable','off',...
                'Position',[550 botTit1-88 40 20]);           

%% Buttons              
pbNext = uicontrol(f,'Style','pushbutton','String','Next',...
                    'FontSize',12,'Position',[585 20 75 30],...
                    'Callback',@pbNext_Callback);
                
pbPreview = uicontrol(f,'Style','pushbutton','String','Preview',...
                    'FontSize',12,'Position',[500 20 75 30],...
                    'Callback',@pbPreview_Callback);                
                
pbCancel = uicontrol(f,'Style','pushbutton','String','Cancel',...
                    'FontSize',12,'Position',[415 20 75 30],...
                    'Callback',@pbCancel_Callback);
              
%% Callback Functions

    function scen_Callback(source,callbackdata)
        scen = get(popScen,'Value');
        if scen == 1 || scen == 2 || scen == 3 || scen == 4
            set(tbfc,'String','2.445','Enable','off')
            set(tbbw,'String','70','Enable','off')
            set(tbIbw,'String','70','Enable','off')
            set(tbtxP,'String','0.65','Enable','off')
            set(tbtxL,'String','0','Enable','off')
            set(tbrxN,'String','4.5','Enable','off')
            set(tbrxL,'String','0','Enable','off')
            set(tbxLoc_ms,'String','0','Enable','off')
            set(tbyLoc_ms,'String','0','Enable','off')
            set(tbms_speed,'String','0','Enable','off')
            set(tbxLoc,'String','10','Enable','off')
            set(tbyLoc,'String','0','Enable','off')
            set(tbcar_speed,'String','30','Enable','off')
            set(poprpat,'Value',1,'Enable','off')
            set(poptm,'Value',2,'Enable','off')
            set(popItm,'Value',2,'Enable','off')
        else
            set(tbfc,'Enable','on')
            set(tbbw,'Enable','on')
            set(tbIbw,'Enable','on')
            set(tbtxP,'Enable','on')
            set(tbtxL,'Enable','on')
            set(tbrxN,'Enable','on')
            set(tbrxL,'Enable','on')
            set(tbxLoc_ms,'Enable','on')
            set(tbyLoc_ms,'Enable','on')
            set(tbms_speed,'Enable','on')
            set(tbxLoc,'Enable','on')
            set(tbyLoc,'Enable','on')
            set(tbcar_speed,'Enable','on')
            set(poprpat,'Enable','on')
            set(poptm,'Enable','on')
            set(popItm,'Enable','on')
        end
     
    end
    
    function pbNext_Callback(source,callbackdata)
       display('Next Pressed')
       
       % RECORD INPUTS
       % General Radar Parameters
       fc = str2double(get(tbfc,'string'))*1e9;
       tmVal = get(poptm,'value');
       tm = str2double(poptmList{tmVal})*1e-3;
       bw = str2double(get(tbbw,'string'))*1e6;
       bw_INT = str2double(get(tbIbw,'string'))*1e6;
       tm_INTVal = get(popItm,'value');
       tm_INT = str2double(popItmList{tm_INTVal})*1e-3;
       
       % Antenna Parameters
       txPower = str2double(get(tbtxP,'string'));
       txLossFactor = str2double(get(tbtxL,'string'));
       rxNF = str2double(get(tbrxN,'string'));
       rxLossFactor = str2double(get(tbrxL,'string'));
       options = load('SampleRadiationPatterns.mat')
       rad_patVal = get(poprpat,'value');
       if rad_patVal == 1
           rad_pat = options.TPLink;
       elseif rad_patVal == 2
           rad_pat = options.samplePatch;
       else
           rad_pat = options.sampleDirectional;
       end
       
       % Main System Parameters
       xLoc_ms = str2double(get(tbxLoc_ms,'string'));
       yLoc_ms = str2double(get(tbyLoc_ms,'string'));
       radar_init_pos = [xLoc_ms;yLoc_ms;0.5];
       radar_speed = str2double(get(tbms_speed,'string'));
       
       % Target Parameters
       xLoc = str2double(get(tbxLoc,'string'));
       yLoc = str2double(get(tbyLoc,'string'));
       car_init_pos = [xLoc;yLoc;0.5];
       car_speed = str2double(get(tbcar_speed,'string'));
       targRange = str2double(get(tbTargRan,'string'));
              
       % Simulation Settings
       Nsweep = str2double(get(tbNumSw,'string'));
       scenType = get(popScen,'value');
       
       
       error = 0;
       % VERIFY ALL INPUTS ARE VALID
       % General Radar Parameters
       if isnan(fc)||fc<2e9||fc>3e9
           error = 1;
       end
       
       if isnan(bw)||bw<1e6||bw>1000e6
           error = 1;
       end
       
       if isnan(radar_speed)||radar_speed<0||radar_speed>100
           error = 1;
       end
       
       if isnan(bw_INT)||bw_INT<1e6||bw_INT>1000e6
           error = 1;
       end
       
       % Antenna Parameters
       if isnan(txPower)
           error = 1;
       end
       
       if isnan(txLossFactor)
           error = 1;
       end
       
       if isnan(rxNF)
           error = 1;
       end
       
       if isnan(rxLossFactor)
           error = 1;
       end
       
       % Target Parameters
       if isnan(xLoc)
           error = 1;
       end
       
       if isnan(yLoc)
           error = 1;
       end
       
%        if isnan(car_speed)||car_speed<0||car_speed>100
%            error = 1;
%        end
       
%        if isnan(targRange)||targRange<1||targRange>100
%            error = 1;
%        end
       
       % Simulation Settings
       if isnan(Nsweep)||Nsweep<8||Nsweep>32
           error = 1;
       end
       
       
       if error == 1 
          errordlg('Check that input values are within ranges.','Invalid Input','modal')
          return
       end
       
       display(scenType)
        
       if scenType == 1
            display('1 Selected');
       elseif scenType == 2
            display('2 Selected');
       elseif scenType == 3
            display('3 Selected');
       elseif scenType == 4
            display('4 Selected');
       else
            close(gcf)
            display('Custom Selected');
            numIntdlg
       end
       display('------------------');
                       
    end

    function pbPreview_Callback(source,callbackdata)
       display('Plot Preview Environment')
       display('------------------');
    end

    function pbCancel_Callback(source,callbackdata)
       display('Program Cancelled')
       display('------------------');
       close(gcf)
       clear all
    end

    
end